SELECT DISTINCT
CITY AS "Город"
TARGET_CITY AS "Унифицированные города"
REG_MANAGER AS "Сотрудник"
FROM cd_salary.rpt_division
WHERE
CURRENT_DATE BETWEEN EFFECTIVE_FROM AND EFFECTIVE_TO
ORDER BY
TARGET_CITY, REG_MANAGER
